# Generated by Django 5.2.7 on 2026-04-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cabang', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cabang',
                'verbose_name_plural': 'Cabang',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mapel', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='TahunAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=9)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tahun Akademik',
                'verbose_name_plural': 'Tahun Akademik',
            },
        ),
        migrations.CreateModel(
            name='Tingkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tingkat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tingkat',
                'verbose_name_plural': 'Tingkat',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.cabang')),
                ('tingkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tingkat')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.matapelajaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.semester')),
            ],
            options={
                'verbose_name': 'Jadwal',
                'verbose_name_plural': 'Jadwal',
            },
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.kelas')),
            ],
            options={
                'verbose_name': 'Santri',
                'verbose_name_plural': 'Santri',
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.matapelajaran')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.santri')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.semester')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='tahun_akademik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tahunakademik'),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alfa', 'Alfa')], max_length=10)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.jadwal')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.santri')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'unique_together': {('santri', 'jadwal', 'tanggal')},
            },
        ),
    ]
