# Generated by Django 6.0.3 on 2026-03-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cabang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tingkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tingkat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.cabang')),
                ('tingkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tingkat')),
            ],
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.kelas')),
            ],
        ),
    ]
