# Generated by Django 5.2.7 on 2026-03-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_matapelajaran_semester_tahunakademik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.AddField(
            model_name='jadwal',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.guru'),
        ),
    ]
