# Generated by Django 5.2.7 on 2026-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_guru_jadwal_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='absensi',
            unique_together={('santri', 'jadwal', 'tanggal')},
        ),
    ]
