from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('santri/', views.santri_list, name='santri_list'),
    path('santri/tambah/', views.santri_tambah, name='santri_tambah'),
    path('santri/edit/<int:id>/', views.santri_edit, name='santri_edit'),
    path('santri/hapus/<int:id>/', views.santri_hapus, name='santri_hapus'),
    path('kelas/', views.kelas_list, name='kelas_list'),
    path('kelas/tambah/', views.kelas_tambah, name='kelas_tambah'),
    path('kelas/edit/<int:id>/', views.kelas_edit, name='kelas_edit'),
    path('kelas/hapus/<int:id>/', views.kelas_hapus, name='kelas_hapus'),
    path('cabang/', views.cabang_list, name='cabang_list'),
    path('cabang/tambah/', views.cabang_tambah, name='cabang_tambah'),
    path('cabang/edit/<int:id>/', views.cabang_edit, name='cabang_edit'),
    path('cabang/hapus/<int:id>/', views.cabang_hapus, name='cabang_hapus'),
    path('cabang/santri/<int:id>/', views.cabang_santri, name='cabang_santri'),
    path('tingkat/', views.tingkat_list, name='tingkat_list'),
    path('tingkat/tambah/', views.tingkat_tambah, name='tingkat_tambah'),
    path('tingkat/edit/<int:id>/', views.tingkat_edit, name='tingkat_edit'),
    path('tingkat/hapus/<int:id>/', views.tingkat_hapus, name='tingkat_hapus'),
    path('absensi/<int:jadwal_id>/', views.absensi_kelas, name='absensi_kelas'),
    path('absensi/', views.absensi_list, name='absensi_list'),
    path('jadwal/', views.daftar_jadwal, name='jadwal'),
    path('jadwal/tambah/', views.jadwal_tambah, name='jadwal_tambah'),
    path('jadwal/edit/<int:id>/', views.jadwal_edit, name='jadwal_edit'),
    path('jadwal/hapus/<int:id>/', views.jadwal_hapus, name='jadwal_hapus'),
    path('guru/', views.guru_list, name='guru_list'),
    path('guru/tambah/', views.guru_tambah, name='guru_tambah'),
    path('guru/edit/<int:id>/', views.guru_edit, name='guru_edit'),
    path('guru/hapus/<int:id>/', views.guru_hapus, name='guru_hapus'),
    path('mata-pelajaran/', views.mata_pelajaran_list, name='mata_pelajaran_list'),
    path('mata-pelajaran/tambah/', views.mata_pelajaran_tambah, name='mata_pelajaran_tambah'),
    path('mata-pelajaran/edit/<int:id>/', views.mata_pelajaran_edit, name='mata_pelajaran_edit'),
    path('mata-pelajaran/hapus/<int:id>/', views.mata_pelajaran_hapus, name='mata_pelajaran_hapus'),
    path('tahun-akademik/', views.tahun_akademik_list, name='tahun_akademik_list'),
    path('tahun-akademik/tambah/', views.tahun_akademik_tambah, name='tahun_akademik_tambah'),
    path('tahun-akademik/edit/<int:id>/', views.tahun_akademik_edit, name='tahun_akademik_edit'),
    path('tahun-akademik/hapus/<int:id>/', views.tahun_akademik_hapus, name='tahun_akademik_hapus'),
    path('semester/', views.semester_list, name='semester_list'),
    path('semester/tambah/', views.semester_tambah, name='semester_tambah'),
    path('semester/edit/<int:id>/', views.semester_edit, name='semester_edit'),
    path('semester/hapus/<int:id>/', views.semester_hapus, name='semester_hapus'),
]