from django.urls import path
from . import views
from . import views_user

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    
    # User Management URLs
    path('user/', views_user.user_list, name='user_list'),
    path('user/tambah/', views_user.user_tambah, name='user_tambah'),
    path('user/edit/<int:id>/', views_user.user_edit, name='user_edit'),
    path('user/hapus/<int:id>/', views_user.user_hapus, name='user_hapus'),
    path('user/detail/<int:id>/', views_user.user_detail, name='user_detail'),
    
    # Santri URLs
    path('santri/', views.santri_list, name='santri_list'),
    path('santri/tambah/', views.santri_tambah, name='santri_tambah'),
    path('santri/edit/<int:id>/', views.santri_edit, name='santri_edit'),
    path('santri/hapus/<int:id>/', views.santri_hapus, name='santri_hapus'),
    path('cabang/', views.cabang_list, name='cabang_list'),
    path('cabang/tambah/', views.cabang_tambah, name='cabang_tambah'),
    path('cabang/edit/<int:id>/', views.cabang_edit, name='cabang_edit'),
    path('cabang/hapus/<int:id>/', views.cabang_hapus, name='cabang_hapus'),
    path('cabang/santri/<int:id>/', views.cabang_santri, name='cabang_santri'),
    path('tingkat/', views.tingkat_list, name='tingkat_list'),
    path('tingkat/tambah/', views.tingkat_tambah, name='tingkat_tambah'),
    path('tingkat/edit/<int:id>/', views.tingkat_edit, name='tingkat_edit'),
    path('tingkat/hapus/<int:id>/', views.tingkat_hapus, name='tingkat_hapus'),
    path('absensi/<int:jadwal_id>/', views.absensi_kelas, name='absensi_kelas'),
    path('absensi/', views.absensi_list, name='absensi_list'),
    path('jadwal/', views.daftar_jadwal, name='jadwal'),
    path('jadwal/tambah/', views.jadwal_tambah, name='jadwal_tambah'),
    path('jadwal/edit/<int:id>/', views.jadwal_edit, name='jadwal_edit'),
    path('jadwal/hapus/<int:id>/', views.jadwal_hapus, name='jadwal_hapus'),
    path('guru/', views.guru_list, name='guru_list'),
    path('guru/tambah/', views.guru_tambah, name='guru_tambah'),
    path('guru/edit/<int:id>/', views.guru_edit, name='guru_edit'),
    path('guru/hapus/<int:id>/', views.guru_hapus, name='guru_hapus'),
    path('mata-pelajaran/', views.mata_pelajaran_list, name='mata_pelajaran_list'),
    path('mata-pelajaran/tambah/', views.mata_pelajaran_tambah, name='mata_pelajaran_tambah'),
    path('mata-pelajaran/edit/<int:id>/', views.mata_pelajaran_edit, name='mata_pelajaran_edit'),
    path('mata-pelajaran/hapus/<int:id>/', views.mata_pelajaran_hapus, name='mata_pelajaran_hapus'),
    path('tahun-akademik/', views.tahun_akademik_list, name='tahun_akademik_list'),
    path('tahun-akademik/tambah/', views.tahun_akademik_tambah, name='tahun_akademik_tambah'),
    path('tahun-akademik/edit/<int:id>/', views.tahun_akademik_edit, name='tahun_akademik_edit'),
    path('tahun-akademik/hapus/<int:id>/', views.tahun_akademik_hapus, name='tahun_akademik_hapus'),
    path('semester/', views.semester_list, name='semester_list'),
    path('semester/tambah/', views.semester_tambah, name='semester_tambah'),
    path('semester/edit/<int:id>/', views.semester_edit, name='semester_edit'),
    path('semester/hapus/<int:id>/', views.semester_hapus, name='semester_hapus'),
    # Kelas URLs
    path('kelas/', views.kelas_list, name='kelas_list'),
    path('kelas/tambah/', views.kelas_tambah, name='kelas_tambah'),
    path('kelas/edit/<int:id>/', views.kelas_edit, name='kelas_edit'),
    path('kelas/hapus/<int:id>/', views.kelas_hapus, name='kelas_hapus'),
    # Penilaian Akademik
    path('nilai/', views.nilai_list, name='nilai_list'),
    path('nilai/tambah/', views.nilai_tambah, name='nilai_tambah'),
    path('nilai/edit/<int:id>/', views.nilai_edit, name='nilai_edit'),
    path('nilai/hapus/<int:id>/', views.nilai_hapus, name='nilai_hapus'),
    path('nilai/mata-pelajaran/<int:mapel_id>/', views.nilai_mata_pelajaran, name='nilai_mata_pelajaran'),
    path('nilai/semester/<int:semester_id>/', views.nilai_semester, name='nilai_semester'),
    path('nilai/santri/<int:santri_id>/', views.nilai_santri, name='nilai_santri'),
    path('nilai/santri/<int:santri_id>/mata-pelajaran/<int:mapel_id>/', views.nilai_santri_mapel, name='nilai_santri_mapel'),
    path('nilai/santri/<int:santri_id>/semester/<int:semester_id>/', views.nilai_santri_semester, name='nilai_santri_semester'),
    
    # Input Nilai Per Semester Workflow
    path('nilai/input/', views.nilai_input_semester, name='nilai_input_semester'),
    path('nilai/input/semester/<int:semester_id>/', views.nilai_input_mapel, name='nilai_input_mapel'),
    path('nilai/input/semester/<int:semester_id>/mapel/<int:mapel_id>/', views.nilai_input_kelas, name='nilai_input_kelas'),
    path('nilai/input/semester/<int:semester_id>/mapel/<int:mapel_id>/kelas/<int:kelas_id>/', views.nilai_input_santri, name='nilai_input_santri'),
    path('nilai/input/simpan/', views.nilai_simpan_batch, name='nilai_simpan_batch'),
    # Rapor
    path('rapor/', views.rapor_list, name='rapor_list'),
    path('rapor/tambah/', views.rapor_tambah, name='rapor_tambah'),
    path('rapor/edit/<int:id>/', views.rapor_edit, name='rapor_edit'),
    path('rapor/detail/<int:id>/', views.rapor_detail, name='rapor_detail'),
    path('rapor/santri/<int:santri_id>/', views.rapor_santri, name='rapor_santri'),
    path('rapor/cetak/<int:id>/', views.rapor_cetak, name='rapor_cetak'),
]
